package com.yutian.minerwar.liveevent;

import com.io.yutian.pixelliveplugin.event.KeyInputEvent;
import com.yutian.minerwar.MinerWar;
import com.yutian.minerwar.manager.GameManager;
import net.royawesome.jlibnoise.module.combiner.Min;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.attribute.Attribute;
import org.bukkit.block.Block;
import org.bukkit.block.Sign;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class KeyInputListener implements Listener {

    public List<UUID> uuidList = new ArrayList<>();
    public boolean resetByMistake = false;

    @EventHandler//点赞
    public void onDianZan(KeyInputEvent e) {
        Player zhubo = e.getPlayer();
        GameManager manager = MinerWar.getGameManager();
        if (manager.isKeyInputd()) {
            zhubo.sendMessage("Modifiers = "+e.getModifiers() + " KeyCode = "+e.getKeyCode()+" RawCode = "+e.getRawCode());
        }
    }
}
